version: "3.5"
services: 
  example-elixir-db-service:
    container_name: example-elixir-db-only
    image: postgres:alpine
    env_file: ./docker/local.env
    volumes:
      - ./docker/database/postgres/data:/var/lib/postgresql/data
      # - ./docker/database/postgres/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    tty: true
    restart: always
    healthcheck:
      #IMPORTANT! change this if you have changed a local.env
      test: ["CMD-SHELL", "pg_isready -U example-elixir-usr -d example-elixir-db"]
      interval: 10s
      timeout: 5s
      retries: 5
  example-elixir-adminer-service:
    container_name: example-elixir-adminer-only
    image: adminer
    restart: always
    ports:
      - 8086:8080
    env_file: ./docker/local.env
    links:
      - example-elixir-db-service
    depends_on:
      - example-elixir-db-service